version: '3.6'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  maristdictionary:
    build: .
    image: maristdictionary
    environment:
      - REDIS_ADDR=localhost
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    restart: unless-stopped
